name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install toolchain
      run: |
        sudo apt install binutils build-essential python device-tree-compiler gcc-arm-linux-gnueabi
        wget https://releases.linaro.org/components/toolchain/binaries/7.3-2018.05/aarch64-linux-gnu/gcc-linaro-7.3.1-2018.05-x86_64_aarch64-linux-gnu.tar.xz
        mkdir -p bin
        tar -xJf gcc-linaro-7.3.1-2018.05-x86_64_aarch64-linux-gnu.tar.xz -C bin/
        rm gcc-linaro-7.3.1-2018.05-x86_64_aarch64-linux-gnu.tar.xz
    - name: Build
      run: |
        make get-repos
        make release
    
