name: release

on:
  push:
    tags:
      - '*'

jobs:
  build_release:
    name: build_release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install toolchain
        run: |
          sudo apt install device-tree-compiler
          wget -q https://releases.linaro.org/components/toolchain/binaries/7.3-2018.05/aarch64-linux-gnu/gcc-linaro-7.3.1-2018.05-x86_64_aarch64-linux-gnu.tar.xz
          mkdir -p bin
          tar -xJf gcc-linaro-7.3.1-2018.05-x86_64_aarch64-linux-gnu.tar.xz -C bin/
          rm gcc-linaro-7.3.1-2018.05-x86_64_aarch64-linux-gnu.tar.xz
      - name: version
        run: echo "::set-output name=version::$(echo $GITHUB_REF | cut -d / -f 3)"
        id: version
      - name: build artifact
        run: |
          make get-repos
          make release
      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ steps.version.outputs.version }}
          tag_name: ${{ github.ref }}
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: upload U-boot-4G artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: release/mochabin-4g-uboot.bin
          asset_name: mochabin-4g-uboot.bin
          asset_content_type: application/octet-stream
      - name: upload U-boot-8G artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: release/mochabin-8g-uboot.bin
          asset_name: mochabin-8g-uboot.bin
          asset_content_type: application/octet-stream
